### ISSUE TITLE
Source language settings 

### ISSUE THREAD

**Issue by AwsMQ** [tachiyomiorg/android-app#11]
Add feature to change language in multi language sources  without changing the entire app language.

**Comment by arkon** [comment]
Are you using v0.10.5? It sounds like you're misunderstanding how to use the app to enable languages in Sources.

This repository isn't for support for 0.x.

**Comment by AwsMQ** [comment]
I use v0.10.5 
I noticed that problem when i tried to use arabic sources
But it won't appear in sources list till changing the app language to arabic 
![20201102_193033](https://user-images.githubusercontent.com/62855009/97899522-13abb800-1d42-11eb-93ea-f6b72c9f0a01.jpg)
![Screenshot_20201102-192902_Tachiyomi](https://user-images.githubusercontent.com/62855009/97899552-20301080-1d42-11eb-8006-2d325d9d67c6.png)
![20201102_193048](https://user-images.githubusercontent.com/62855009/97899578-27571e80-1d42-11eb-979a-4ee906193eba.jpg)

**Comment by arkon** [comment]
You need to enable Arabic from the three line icon at the top.

If you have further questions, try asking on Discord.

**Comment by AwsMQ** [comment]
Worked like charm, Thanks
