### ISSUE TITLE
[BUG] Downloads list not adding updates when downloading something

### ISSUE THREAD

**Issue by gjstos** [tachiyomiorg/android-app#4]
As the title of the issue already says ...

I realized that it is not being added to the queue of Downloads items that have received update when there are already other items added manually by downloading.

**Comment by loocool2** [comment]
this isn't a bug. enable auto download new chapters.

**Comment by CarlosEsco** [comment]
Why are you opening issues on a in development 1.x?

**Comment by gjstos** [comment]
> this isn't a bug. enable auto download new chapters. this isn't even the right repo for it.

It's enabled :/.
